# Generated by Django 3.2.9 on 2022-01-08 07:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hospital_cont',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_cont',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
