# Generated by Django 3.2.9 on 2022-01-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0002_auto_20220108_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
    ]
