# Generated by Django 3.2.9 on 2022-01-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighboor', '0004_business_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
